[package]
name = "rust-singletone"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
soapysdr = "0.3.2"
num = "0.4"
num-traits = "0.2.15"
GSL = "6.0"
byteorder = "1.4.3"
